### ISSUE TITLE
Support for large files

### ISSUE THREAD

**Issue by pietervanheijningen** [ToX82/logHappens#3]
Hey!

I've got some pretty big log files that I want to view (32 mil+ lines).
But it seems like the application loads the entire file in at once and then generates the pages in the frontend. Wouldn't it be nicer if it only loads the content needed for the first page? I can't even get a file with 20k lines to load in now without the browser crashing. Therefore it seems hard to actually use it.

Other than that the application is pretty cool though!

**Comment by ToX82** [comment]
I love your idea! Parsing the whole file in order to see only a small subset is indeed a waste.

Due to the different format of log files (and the fact that they are parsed on the fly) it's not an easy thing to do though... I'll see if I can come up to something. Meanwhile, if you have any idea and want to make a pull request I'd be very glad to merge it.

**Comment by ToX82** [comment]
I've just pushed a new release addressing this issue :) Please let me know if it works for you. Keep in mind that parsing 32M lines is a big task though, so it could still be a bit slow. Not too much hopefully!


Btw there are a few other changes to the codebase, and you might need to update your configuration file. Please see the new config.default.json (https://github.com/ToX82/logHappens/blob/master/config.default.json) for an example.

**Comment by pietervanheijningen** [comment]
Very cool! It works!

One small problem though, it seems like the auto refresh function seems to make it reset to the current page. Think it would be nice to make the autorefresh stop once you go off the first page. i'll try and see if i can fix it and make a PR
